###################################################
# API: Bill Controller
# Archivo de pruebas para facturación
# Crea facturas a partir del carrito de compras
###################################################


###################################################
# 1. Generar una factura
#    Se debe enviar el "shoppingCart_id".
#    El backend sumará automáticamente el valor
#    total de todos los ítems del carrito.
###################################################
POST http://localhost:8000/api/bills
Accept: application/json
Content-Type: application/json

{
    "shoppingCart_id": 1
}


###################################################
# 2. Obtener una factura específica
#    Reemplazar {id} por el ID real de la factura.
###################################################
GET http://localhost:8000/api/bills/1
Accept: application/json


###################################################
# 3. Eliminar una factura existente
###################################################
DELETE http://localhost:8000/api/bills/1
Accept: application/json
